version: "3.8"
services:
  web:
    build: ./app
    command: 536697238680.dkr.ecr.us-east-2.amazonaws.com/djano_docker_aws_web
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    image: 536697238680.dkr.ecr.us-east-2.amazonaws.com/djano_docker_aws_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:


